---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: webapp-common
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  validation: client

