---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: webapp-backend
  namespace: flux-system
spec:
  dependsOn:
  - name: webapp-common
  interval: 2m0s
  path: ./k8s/backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  validation: client

